#!/bin/zsh
# For license info see http://unlicense.org/

# This script locates any flac file without replaygain tags and
# produces the script "fixcommands" which I run to add those tags.
rm -f dirlist fixcommands

# Where the config file is stored.
config="~/.config/muzshic/config"

if [[ -r ${~config} ]]; then
    source ${~config}
else
    print 'run genconfig to generate a configuration file.' >&2
    exit 0
fi


dirs="$1"
if [[ $dirs == "" ]]; then
    dirs=${~database}
fi

find ${~dirs} -name '*.flac'| \
    while read i; do
        if [ -z "$(metaflac --show-tag=REPLAYGAIN_TRACK_GAIN $i)" ]; then
            echo "$i has no replaygain info :-/"
            echo "${i%/*}" >> dirlist
        fi
    done

if [ -r dirlist ]; then
    echo '#!/bin/sh -x' > fixcommands
    sort -i dirlist | uniq | \
        while read dir; do
            cat << EOF >> fixcommands
cd "$dir"
metaflac --add-replay-gain *.flac
EOF
        done
    rm dirlist
    echo "Do examine and then run ./fixcommands"
else
    echo "How boring! Nothing to be done."
fi
