#!/bin/zsh
# For license info see http://unlicense.org/

# This script locates any flac file without replaygain tags and
# produces the script "fixcommands" which I run to add those tags.
rm -f dirlist fixcommands
find /mp3/{4ad,HipHop,Jazz,Klassiek,Metal,Pop,Soundtracks} -name '*.flac'| \
    while read i; do
        if [ -z "$(metaflac --show-tag=REPLAYGAIN_TRACK_GAIN $i)" ]; then
            echo "$i has no replaygain info :-/"
            echo "${i%/*}" >> dirlist
        fi
    done

if [ -r dirlist ]; then
    echo '#!/bin/sh -x' > fixcommands
    sort -i dirlist | uniq | \
        while read dir; do
            cat << EOF >> fixcommands
cd "$dir"
chmod 644 *.flac
metaflac --add-replay-gain *.flac
chmod 444 *.flac
EOF
        done
    rm dirlist
    echo "Hmmm, still some work to do..."
else
    echo "How boring! Nothing to be done."
fi
