#!/bin/zsh
# For license info see http://unlicense.org/

# This script locates any flac file without replaygain tags and
# produces the script "fixcommands" which I run to add those tags.
rm -i dirlist
rm -i fixcommands

# Where the config file is stored.
config="~/.config/muzshic/config"

if [[ -r ${~config} ]]; then
    source ${~config}
else
    print 'run genconfig to generate a configuration file.' >&2
    exit 0
fi


dirs="$1"
if [[ $dirs == "" ]]; then
    dirs=${~database}
fi

echo 'Finding all directories'
for d in $(find ${~dirs} -type d); do
    echo -n "$d                               " # xxx
    echo -ne '\r'
    #
    find $d -maxdepth 1 -type f \
         -name '*.mp3'  -o -name '*.dff'  -o  -name '*.mpc' -name '*.m4a' -o -name '*.ogg'  -o  -name '*.flac' -o -name '*.ape' -o -name '*.aac' -name '*.opus' -o -name '*.wav' |\
        while read i; do
            if ! bs1770gain -l "$i" 2>&1 | /bin/grep -q REPLAYGAIN_ALBUM_ ; then
                echo "$i has no replaygain info :-/"
                echo "${i%/*}" >> dirlist
            fi
        done
done

if [ -r dirlist ]; then
    cat << EOF > fixcommands
#!/bin/zsh -x

foobar()
{
    rsync -avP *.mp3 ~/mp3
    cd ~/mp3
    bs1770gain -o foo *.mp3 || return
    chmod 644 foo/*
    mv -f foo/* .
    rmdir foo
    cd -
    rsync -avP ~/mp3/ .
    rm ~/mp3/*.mp3
    chmod 644 *.mp3
}

EOF
    sort -i dirlist | uniq | \
        while read dir; do
            cat << EOF >> fixcommands
(cd "$dir" && foobar)
EOF
        done
    rm dirlist
    chmod +x fixcommands
    echo "Do examine and then run ./fixcommands"
else
    echo "How boring! Nothing to be done."
fi
