#!/bin/zsh
# for i in 4ad HipHop Jazz Klassiek Metal Pop Soundtracks

for i in $(find . -type d); do
    (
        cd "$i"
        ls cover.jpg >& /dev/null && continue
        ls .nca  >& /dev/null && continue
        ls *' 01 '*  >& /dev/null || continue
        artist="$(exiftool -p '$ARTIST' *' 01 '*)"
        album="$(exiftool -p '$ALBUM' *' 01 '*)"

        if glyrc cover --artist "$artist" --album "$album" --write 'cover.:format:'; then
            if [[ -e cover.png ]]; then
                convert cover.png cover.jpg
                rm cover.png
            fi
            if [[ -e cover.jpeg ]]; then
                mv cover.jpeg cover.jpg
            fi
        else
            touch .nca
        fi
    )
done
