#!/bin/zsh
for i in log cue m3u nfo sfv m3u ffp accurip rtf CUE; do
    find . -maxdepth 1 -type f -name "*.$i" -delete
done

mid3v2 -D *.flac

while :; do
    if ! pgrep -f 'puddletag ' >& /dev/null; then
        break
    fi
    echo -n '.'
    sleep 5
done

cd .

DISPLAY=:0.0 puddletag .
# DISPLAY=:0.0 /usr/pkgmk/source/puddletag3/source/puddletag .
coverart

if [[ $1 == -l ]]; then
    lyrics
fi

nice -n 19 replaygain
album="$(metaflac --show-tag=album *' 01 '*)"
album="${album#album=}"

cd ~/incoming
mv "$album" ~/done/
chmod -R g+w ~/done/
echo -e '\a'
