#!/bin/zsh
for i in log cue m3u nfo sfv m3u ffp accurip rtf CUE; do
    find . -maxdepth 1 -type f -name "*.$i" -delete
done

mid3v2 -D *.flac

echo "Checking for broken flac files, just a moment."
find . -type f -iname '*.flac' -print0 | xargs -0 flac -wst > broken_flac.log 2>&1

if [[ -s broken_flac.log ]]; then
    echo "Broken flacs detected." >&2
    cat broken_flac.log
    exit 1
else
    rm broken_flac.log
fi

while :; do
    if ! pgrep -f 'puddletag ' >& /dev/null; then
        break
    fi
    echo -n '.'
    sleep 5
done

cd .

puddletag .
coverart

if [[ $1 == -l ]]; then
    lyrics
fi
if [[ $1 == -L ]]; then
    lyrics -L
fi

dr14_tmeter
spectrogram

nice -n 19 replaygain
album="$(metaflac --show-tag=album *' 01 '*)"
album="${album#album=}"

# Don't move it if it's already in /music
if ! pwd | grep -q /music; then
    cd ../
    mv "$album" ~/done/
    chmod -R g+w ~/done/
fi
echo -e '\a'
