#!/bin/zsh

# Copyright 2015 Han Boetes <han@boetes.org>
# For license info see http://unlicense.org/

# I used this script to play the first second of the first flac file
# of each directory to hunt for a bug.

zgrep '[ 1]01.*flac$' /mp3/playlist.m3u.gz > flaclist

l=$(wc -l < flaclist)

for i in {1..$l}; do
    tt="$(sed -ne ${i}p flaclist)"
    echo "$tt"
    mplayer -endpos 1 "$tt" > /dev/null
done
