#!/bin/zsh
# Copyright 2017-2020 Han Boetes <han@boetes.org>
# For license info see http://unlicense.org/

# Check for dependencies.
for i in exiftool metaflac glyrc; do
    if ! command -v $i >& /dev/null; then
        faileddep=true
        echo "I need $i, please install it."
    fi
done

if [[ $faileddep == true ]]; then
    exit 1
fi

readtag ()
{
    exiftool -q -q -p '$'$1 $2
}

get_lyrics()
{
    artist="$(readtag artist $1)"
    album="$(readtag album $1)"
    title="$(readtag title $1)"
    # LinksNominate is the most common crap found in lyrics.
    glyrc lyrics -a "$artist" -b "$album" -t "$title" -w "${1}.txt" || echo 'Instrumental' > "${1}.txt"
    sed -i -n "/linksNominate/q;p" "${1}.txt"
    sed -i -n "/^Credits/q;p" "${1}.txt"
}

write_flac_lyrics()
{
    metaflac --set-tag-from-file="lyrics=${1}.txt" "$1"
    rm "${1}.txt"
}

write_mp3_lyrics()
{
    eyeD3 --add-lyrics "${1}.txt" "$1"
    rm "${1}.txt"
}


print_title()
{
    cat << EOF
+-------------
| $1
+-------------
EOF
}


case $1 in
    *.flac)
        if [[ -z $(readtag lyrics "$1") ]]; then
            get_lyrics "$1"
            write_flac_lyrics "$1"
        fi
        print_title "$1"
        readtag lyrics "$1"
        ;;
    *.mp3)
        if [[ -z $(readtag lyrics "$1") ]]; then
            get_lyrics "$1"
            write_mp3_lyrics "$1"
        fi
        print_title "$1"
        readtag lyrics "$1"
        ;;
    '')
        for i in *.(mp3|flac); do
            $0 $i
        done
        ;;
    *)
        echo "So far I can do flac and mp3 files."
        exit 1
        ;;
esac
