#!/bin/zsh
# Copyright 2015 Han Boetes <han@boetes.org>
# For license info see http://unlicense.org/

# This script generates a very simple database of all my music files.

unset  LC_ALL
export LC_COLLATE=C
export LANG=en_US.UTF-8

config="~/.config/muzshic/config"

if [[ -r ${~config} ]]; then
    source ${~config}
else
    print 'run genconfig to generate a configuration file.' >&2
    exit 0
fi

touch $playlist.new || exit 1

if [[ $1 == -f ]]; then
    database=($(find ${~database}  -maxdepth 1 -mindepth 1 -type d -mmin -60))
    if [[ -n "$database" ]]; then
        database=($(find ${~database}  -maxdepth 1 -mindepth 1 -type d -mmin -60))
    fi
    if [[ -z "$database" ]]; then
        echo "No new files found."
        exit 0
    fi
fi

# Generate the search options for find from the supported filetypes
for i in $filetypes; do
    st="$st -name '*'.$i -o"
done
# remove trailing -o
st=${st% -o}

set -x
time eval find ${~database} -type f  $st | sort -n | gzip -c > $playlist.new

set +x

if [[ $1 == -f ]]; then
    zcat $playlist $playlist.new | sort -n | gzip -c > $playlist.newest
    mv $playlist.newest $playlist.new
fi
if [ -e $playlist ]; then
    # If zdiff returns an error, it's because a difference has been found.
    (zdiff -u $playlist $playlist.new || : )| colordiff | less -R || print "Consider installing diff and colordiff" >&2
fi
mv -f ${playlist}.new $playlist
zgrep -E '\.(wav|ape)$' $playlist
