#!/bin/zsh
# Copyright 2015 Han Boetes <han@boetes.org>
# For license info see http://unlicense.org/

# This script generates a very simple database of all my music files.

config="~/.config/muzshic/config"

# To get error messages down the pipe.
setopt pipefail

if [[ -r ${~config} ]]; then
    source ${~config}
else
    print 'run genconfig to generate a configuration file.' >&2
    exit
fi

find ${~database} \
    -type f \
    -name '*.mp3'  -o \
    -name '*.ogg'  -o \
    -name '*.flac' -o \
    -name '*.ape'  -o \
    -name '*.mpc' | sort -n | gzip -c > $playlist.new
if [ -e $playlist ]; then
    zdiff -u $playlist $playlist.new | colordiff | less -R || print "Consider installing diff and colordiff" >&2
fi
mv -f ${playlist}.new $playlist
