#!/bin/zsh -e
source="$(find /home/nicotine/done/ -type d -mindepth 1|head -n 1)"
if [[ -z "$source" ]]; then
    echo "Nothing to do!"
    exit 0
fi
artist="$(metaflac --show-tag=artist $source/*' 01 '*)"
artist="${artist#artist=}"
dir=$(ls -d /mp3/*/"$artist")
if [[ -z "$dir" ]]; then
    echo "I don't know the artist $artist, please create a $dir for them."
    exit 0
fi
set -x
rsync -v --info=progress2 --partial -rlptD "$source" "$dir"
set +x
chmod -R g-w "$dir"
rm -rf "$source"
