#!/bin/zsh

getdirs()
{
    zgrep "${1:=mp3}\$" /music/playlist.gz| while read line; do
        line=${line#*/}
        line=${line#*/}
        line=${line#*/}
        line=${line%/*}
        echo ${line//\// }
    done
}
getdirs $1 | uniq
