#!/bin/zsh
for i in $(find . -type d); do
    # echo $i
    (
        cd "$i"
        if [[ ! -e shazam.txt ]]; then
            if ls *" "01" "*.flac > /dev/null 2>&1; then
                songrec audio-file-to-recognized-song *" "01" "*.flac > shazam.txt
            else
                echo "$i"
            fi
        fi
    )
done
