#!/bin/zsh

if ! command -v sox >& /dev/null; then
    echo "No sox installed, that sox!" >&2
    exit 1
fi

if [[ -f spectrogram.png ]]; then
    echo 'spectrogram.png already exists' >&2
    exit 1
fi

if [[ -z $1 ]]; then
    i="*.flac"
else
    i="$1"
fi

sox "$i" -n spectrogram -w kaiser -t $i
