#!/bin/zsh

if ! command -v sox >& /dev/null; then
    echo "No sox installed, that sox!" >&2
    exit 1
fi

if [[ -f spectrogram.png ]]; then
    echo 'spectrogram.png already exists' >&2
    exit 1
fi

if [[ -z $1 ]]; then
    i="*.flac"
else
    i="$1"
fi

first_file=$(ls ${~i}|head -1)
artist=$(metaflac --show-tag=artist $first_file|awk -F '=' '{print $2}')
album=$(metaflac --show-tag=album $first_file|awk -F '=' '{print $2}')

sox $i -n spectrogram -x 1600 -Y 1000 -t "$artist — $album"
